services:
  migrations:
    build:
      context: .
      dockerfile: migrations/Dockerfile

    command: ["/goose", "up"]
    tty: true

    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgres://tests:tests@postgres:5432/tests
      GOOSE_MIGRATION_DIR: .
      GOOSE_TABLE: goose_migrations

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    networks:
      - test-network

  redis:
    image: redis:latest
    restart: unless-stopped
    command: redis-server --loglevel warning
    ports:
      - "19875:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 5s
   
  postgres:
    image: postgres:18
    command: ["postgres", "-c", "log_statement=all"]
    restart: always
    environment:
      POSTGRES_USER: tests
      POSTGRES_PASSWORD: tests
      POSTGRES_DB: tests
    ports:
      - "19876:5432"
    volumes:
      - postgres_data_tests:/var/lib/postgresql/18/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tests -d tests"]
      interval: 2s
      timeout: 2s
      retries: 10

    networks:
      - test-network

volumes:
  postgres_data_tests:
    name: urlshortener_postgres_tests_data
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  test-network:
    driver: bridge
